/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppModal: typeof import('./components/common/AppModal.vue')['default']
    AppSidebar: typeof import('./components/business/AppSidebar.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    LoadingState: typeof import('./components/common/LoadingState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/common/StatCard.vue')['default']
  }
}
