/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentConfigDrawer: typeof import('./src/components/AgentConfigDrawer.vue')['default']
    AICore: typeof import('./src/components/AICore.vue')['default']
    BlurredBubbles: typeof import('./src/components/BlurredBubbles.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CarouselCard: typeof import('./src/components/CarouselCard.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    DummyCard: typeof import('./src/components/dummyCard.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EmotionBall: typeof import('./src/components/EmotionBall.vue')['default']
    FloatingParticles: typeof import('./src/components/FloatingParticles.vue')['default']
    GeoNexusGlobe: typeof import('./src/components/GeoNexusGlobe.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    ParticleGlobe: typeof import('./src/components/ParticleGlobe.vue')['default']
    RichEditor: typeof import('./src/components/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sideBar.vue')['default']
    StellarDotsBand: typeof import('./src/components/StellarDotsBand.vue')['default']
    Wave: typeof import('./src/components/wave.vue')['default']
  }
}
